### ISSUE TITLE
global name 'DEBUG' is not defined when trying to validate

### ISSUE THREAD

**Issue by yangkennyk** [mschmidtkorth/alfred-clickup-msk#13]
**Describe the bug**
validate configuration doesn't work

**To Reproduce**
using the validate command

**Expected behavior**
for it to validate

**Alfred version**
4.0.8

**Debug log**
`[11:44:50.006] ERROR: ClickUp[Script Filter] Code 1: .
11:44:49 workflow.py:2061 DEBUG    ---------- ClickUp (1.0.5) ----------
11:44:49 workflow.py:2080 ERROR    global name 'DEBUG' is not defined
Traceback (most recent call last):
  File "/Users/MYUSERNAME/Dropbox/alfred_preferences/Alfred.alfredpreferences/workflows/user.workflow.5A3471A3-A9E3-4314-8056-9D4ADCC8DEFC/workflow/workflow.py", line 2073, in run
    func(self)
  File "config.py", line 18, in main
    configuration()
  File "config.py", line 127, in configuration
    wf3.add_item(title = 'Checking API Key: ' + ('✓' if checkClickUpId('list', 'confList') else '✗'), valid = True, arg = 'cu:config ')
  File "config.py", line 191, in checkClickUpId
    if DEBUG > 0:
NameError: global name 'DEBUG' is not defined
11:44:49 workflow.py:2103 DEBUG    ---------- finished in 0.003s ----------`

**Screenshots**
attached

**Additional context**
Alfred workflows are stored in dropbox folder

![image](https://user-images.githubusercontent.com/6680040/75697437-13bb5b80-5c7b-11ea-8806-9e6ba5b6c24b.png)

**Comment by mschmidtkorth** [comment]
Hi @yangkennyk thanks for reporting this!

I have fixed it, could you give it a try? I will release it once confirmed.

[ClickUp-1.0.6.alfredworkflow.zip](https://github.com/mschmidtkorth/alfred-clickup-msk/files/4303186/ClickUp-1.0.6.alfredworkflow.zip)

**Comment by yangkennyk** [comment]
looks to be working for me now. thanks! 🤘
