### ISSUE TITLE
Validation gives error

### ISSUE THREAD

**Issue by drawesome** [mschmidtkorth/alfred-clickup-msk#15]
I've added all necessary api key and list/space id's but when I click validate I get the following error:

Error in workflow ‘ClickUp’
Coercing to Unicode: need string or buffer, NoneType found

Your Alfred version.  
4.0.9 [1144]

**Comment by drawesome** [comment]
I can search existing project/tasks no problem... but I can't CREATE new tasks if that helps

**Comment by drawesome** [comment]
I got it working after I added the 'folder' parameter.... seems it's NOT optional

**Comment by mschmidtkorth** [comment]
@drawesome Good catch! I've fixed that, the Folder will now only be validated if it is set.
