### ISSUE TITLE
Setting a time doesn't work with @today @tomorrow

### ISSUE THREAD

**Issue by vlom31** [mschmidtkorth/alfred-clickup-msk#23]
**Describe the bug**

I like using the workflow for entering in events that I want to attach a specific time to, and it works great for dates in the future, but when setting up meetings for today or tomorrow I usually prefer using the shortcut which I find super helpful, but when using the shortcuts, the time is not recognized.

**Alfred version**
4.3

**Debug log**
`[15:18:49.838] ClickUp[Script Filter] Queuing argument 'test @today 14.00'
[15:18:50.102] ClickUp[Script Filter] Script with argv 'test @today 14.00' finished
[15:18:50.115] STDERR: ClickUp[Script Filter] .
15:18:50 workflow.py:2061 DEBUG    ---------- ClickUp (1.1.0) ----------
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 workflow.py:2343 DEBUG    update check not due
15:18:50 main.py:597 DEBUG    [ main() ] - test @today 14.00
15:18:50 main.py:220 DEBUG    [ firstRun() ]
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 workflow.py:2225 DEBUG    last run version: 1.1.0
15:18:50 workflow.py:2225 DEBUG    last run version: 1.1.0
15:18:50 main.py:235 DEBUG    [ checkConfig() ]
15:18:50 workflow.py:2461 DEBUG    got password : com.msk.clickup2.0:clickUpAPI
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 main.py:361 DEBUG    [ getNameFromInput() ] 
15:18:50 main.py:364 DEBUG    inputName: test
15:18:50 main.py:376 DEBUG    [ getContentFromInput() ] 
15:18:50 main.py:382 DEBUG    inputContent: 
15:18:50 main.py:394 DEBUG    [ getTagsFromInput() ] 
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 main.py:408 DEBUG    inputTags: []
15:18:50 main.py:435 DEBUG    [ getDueFromInput() ] 
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 main.py:475 DEBUG    Received relative date: 2021-01-13 15:18:50.030172
15:18:50 main.py:476 DEBUG    2021-01-13 15:18:50.030213
15:18:50 main.py:538 DEBUG    inputDue: 2021-01-13 15:18:50.030172
15:18:50 main.py:553 DEBUG    [ getListFromInput() ] 
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 main.py:563 DEBUG    inputList: 10985217
15:18:50 main.py:564 DEBUG    {}
15:18:50 main.py:576 DEBUG    [ getPriorityFromInput() ] 
15:18:50 main.py:584 DEBUG    inputPriority: None
15:18:50 main.py:275 DEBUG    [ addCreateTaskItem() ]
15:18:50 workflow.py:1468 DEBUG    reading settings from /Users/mac/Library/Application Support/Alfred/Workflow Data/com.msk.clickup2.0/settings.json
15:18:50 main.py:311 DEBUG    [ formatNotificationText() ] 
15:18:50 main.py:350 DEBUG    [ formatDate() ] 
15:18:50 main.py:250 DEBUG    [ checkUpdates() ]
15:18:50 workflow.py:1695 DEBUG    loading cached data: /Users/mac/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.msk.clickup2.0/__workflow_latest_version.cpickle
15:18:50 workflow.py:2254 DEBUG    set last run version: 1.1.0
15:18:50 workflow.py:2103 DEBUG    ---------- finished in 0.024s ----------
[15:18:50.117] ClickUp[Script Filter] {"items": [{"arg": "{\"inputDue\": \"2021-01-13 15:18:50.030172\", \"inputContent\": \"\", \"inputPriority\": null, \"inputName\": \"test\", \"inputList\": null, \"inputTags\": []}", "valid": true, "subtitle": "\ud83d\udcc52021-01-13 15:18 ", "variables": {"isSubmitted": "true"}, "title": "Create task \"test\"?"}]}`

**Screenshots**

Works when entering full date (time is set to 14:00 correctly) : 
![works](https://dsc.cloud/cb4a72/Screen-Shot-2021-01-13-15-13-46.jpg)

Doesn't work when using @today (time is not set) : 
![Doesn't work](https://dsc.cloud/cb4a72/Screen-Shot-2021-01-13-15-13-23.jpg)

**Additional context**

**Comment by mschmidtkorth** [comment]
Hi @vlom31 thanks for reporting that - indeed, the time when using a relative date was not recognized correctly.

I've fixed that (as attached), would you please let me know whether it is working for you? Simply extract the file and open the `.alfredworkflow` file. 

[ClickUp-1.1.2.alfredworkflow.zip](https://github.com/mschmidtkorth/alfred-clickup-msk/files/5810485/ClickUp-1.1.2.alfredworkflow.zip)

**Comment by vlom31** [comment]
Thank you @mschmidtkorth I just got the workflow update and it's working great now with relative dates too 👍 🙏

**Comment by 1activegeek** [comment]
I'm not sure if this is the same issue or something different, but I'm running into an issue trying to just use `@tod` as well. In my case, no date, and it tells me the time is incorrect. But if I was to specify `@tue` it works fine. 

Looks like it will work
<img width="578" alt="image" src="https://user-images.githubusercontent.com/6810720/110357609-758a7000-8009-11eb-8ecb-bdb611669fca.png">

Doesn't work as soon as a space is entered
<img width="573" alt="image" src="https://user-images.githubusercontent.com/6810720/110357646-80450500-8009-11eb-8cdc-5cab8b23e06b.png">

Works fine with and without the space using a day
<img width="581" alt="image" src="https://user-images.githubusercontent.com/6810720/110357679-8aff9a00-8009-11eb-8c52-2aa3826157e2.png">

**Comment by vlom31** [comment]
@1activegeek I don't think @tod is a valid shortcut for dates, try @today @tomorrow

**Comment by 1activegeek** [comment]
@vlom31 same results either way - based on the date showing underneath when I have `@tod` with no space, it seemed like it should be working. It shows the EXACT same behavior when I used `@today` as well. Without a space, it shows the date and looks like it will work, as soon as a space is placed at the end, it shows `Not a valid time.`

**Comment by 1activegeek** [comment]
Just following up on this with some more detail/information - I believe the issue may stem from the fact that it seems it is looking for a time, and not receiving one and running into an issue processing the space as a time designation. I'll open a new request anyway as this was uncovered when I saw that using `@today` with no space at the END of my tasks works. With this however, it is inserting the TOD that the task is being entered, even though I wish it to just be no time associated, just the day.
