### ISSUE TITLE
Open in desktop app

### ISSUE THREAD

**Issue by pat-s** [mschmidtkorth/alfred-clickup-msk#30]
Thanks for this workflow!

I was wondering if there is an option to open links in the desktop app instead of the browser.

If not and support is planned, there could be a user setting in the config to set a preference.

**Comment by pat-s** [comment]
Seems like this an upstream thingy: https://clickup.canny.io/feature-requests/p/open-links-in-app-not-web

**Comment by mschmidtkorth** [comment]
Indeed, unfortunately you cannot open links directly in the app. I'd love for this to be possible!
